# MiniChatAnnouncer
#                                                                           
# To modify the plugin messages and to use the plugin in general, 
# I recommend that you have a basic knowledge of MiniMessage.
# Guide: https://docs.adventure.kyori.net/minimessage.html#format
# Spanish Guide: https://gist.github.com/4drian3d/9ccce0ca1774285e38becb09b73728f3
#
# Plugin messages
messages:
  chat:
    # Message displayed when the chat has been displayed successfully.
    successfully: "<gray>[</gray><gradient:yellow:blue>MiniChatAnnouncer</gradient><gray>]</gray> <green>Message succesfully sended</green>"
    # Message to send to the player in case he does not have the respective permission.
    no-permission: "<gray>[</gray><gradient:yellow:blue>MiniChatAnnouncer</gradient><gray>]</gray> <red>You do not have permission to execute this command</red>"
    # Message to be sent when executing the /sendchat command and only the player is specified.
    only-player: "<gray>[</gray><gradient:yellow:blue>MiniChatAnnouncer</gradient><gray>]</gray> <gray>You must enter the message to be sent after the player's name.</gray>"
    # This message will be displayed if a player with the name specified in /sendchat is not found.
    player-not-found: "<gray>[</gray><gradient:yellow:blue>MiniChatAnnouncer</gradient><gray>]</gray> <red>Player not found</red>"
# Plugin sounds
# In the sound-id field you must enter a valid value from: 
# https://minecraft.fandom.com/wiki/Sounds.json/Java_Edition_values
sounds:
  chat:
    # Enable sounds when using chats 
    enabled: true
    # ID of the sound to be used
    sound-id: "entity.experience_orb.pickup"
    # Volume of sound
    volume: 10
    # Pitch of the sound
    pitch: 2
